### PR TITLE
Updates orbit-db-keystore to use indexeddb

### PR DESCRIPTION
**Pull request by AlbertoElias**
PR to bring in https://github.com/orbitdb/orbit-db-keystore/pull/17

### CODE REVIEW

**Comment by AlbertoElias** [comment]
Could we get this merged? It's to libp2p and that way I can test everything in my project

**Comment by aphelionz** [comment]
Sure, this may already be in master in a different form - can you repoint this to master so we can have a look?

**Comment by AlbertoElias** [comment]
@aphelionz I didn't know it was so easy to repoint the base branch! I've done so now

**Comment by aphelionz** [comment]
Great, thank you! We will have a closer look at this ASAP

**Comment by aphelionz** [comment]
@shamb0t Can you take a look at this when you get a chance? My feeling is that this has already been implemented in 0.20.0 but just want to make sure we haven't missed anything

**Comment by shamb0t** [comment]
@AlbertoElias @aphelionz indeed already implemented. `Keystore.create`no longer needs `await` as `store.open` isn't called until the storage is interacted with. @AlbertoElias are you able to test your project using the `master` branch or `orbit-db@0.20.0-rc.1`?

**Comment by aphelionz** [comment]
Closing as this is taken care of 🙂

**Pull request closed without merging**
