### PR TITLE
Use LevelDB as the local cache

### PR DESCRIPTION
**Pull request by haadcode**

### CODE REVIEW

**Comment by haadcode** [comment]
This PR will make OrbitDB use LevelDB as its local cache (as opposed to previous fs-blob-storage).

This is a breaking change since the local data file structure will change with this change. However, we do gain a considerable performance improvement.

**Comment by shd101wyy** [comment]
Hi there, I don't know whether this is caused by switching to leveldb or not. I am using orbit-db in browser but after I upgraded it to version `0.18.12`, it stopped working and showed me that:

```
bindings.js:158 Uncaught TypeError: exists is not a function
    at Function.getRoot (bindings.js:158)
    at bindings (bindings.js:60)
    at Object.<anonymous> (leveldown.js:4)
    at __webpack_require__ (bootstrap 4ba5e5c24f442b3c8a6f:19)
    at Object.<anonymous> (level.js:1)
    at __webpack_require__ (bootstrap 4ba5e5c24f442b3c8a6f:19)
    at Object.<anonymous> (Cache.js:5)
    at __webpack_require__ (bootstrap 4ba5e5c24f442b3c8a6f:19)
    at Object.<anonymous> (OrbitDB.js:10)
    at __webpack_require__ (bootstrap 4ba5e5c24f442b3c8a6f:19)
```

Besides, when I run webpack to build javascript file, it gives me warnings:

```
WARNING in ./node_modules/bindings/bindings.js
81:22-40 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/bindings/bindings.js
 @ ./node_modules/level/node_modules/leveldown/leveldown.js
 @ ./node_modules/level/level.js
 @ ./node_modules/orbit-db-cache/Cache.js
 @ ./node_modules/orbit-db/src/OrbitDB.js
 @ ./src/lib/user.ts
 @ ./src/components/app.tsx
 @ ./src/index.tsx

WARNING in ./node_modules/bindings/bindings.js
81:43-53 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/bindings/bindings.js
 @ ./node_modules/level/node_modules/leveldown/leveldown.js
 @ ./node_modules/level/level.js
 @ ./node_modules/orbit-db-cache/Cache.js
 @ ./node_modules/orbit-db/src/OrbitDB.js
 @ ./src/lib/user.ts
 @ ./src/components/app.tsx
 @ ./src/index.tsx
```

This is my webpack config file:

```javascript
const path = require('path')
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
  entry: {
    main: path.resolve(__dirname, './src/index.tsx'),
    sw: path.resolve(__dirname, './src/service_worker/sw.ts')
  },
  output: {
    path: path.resolve(__dirname, './'),
    filename: '[name].bundle.js',
  },
  target: 'web',
  devtool: 'source-map',
  externals: {
    fs: '{}',
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.less', '.css']
  },
  module: {
    loaders: [ 
      { test: /\.tsx?$/, loader: 'awesome-typescript-loader' },
      { test: /\.less$/, loader: "style-loader!css-loader!less-loader"},
      { test: /\.css$/, loader: "style-loader!css-loader"},      
      { test: /\.json$/, loader: "json-loader"}
    ]
  },
  plugins: [
  ]
}
```

Thanks

**Comment by mmick66** [comment]
It seems to be related with [issues](https://github.com/Level/level/issues/34) in LevelDB

**Comment by haadcode** [comment]
@shd101wyy thanks for reporting the issue!

It sounds to me this might be caused by an old version of OrbitDB:
> ...after I upgraded it to version 0.18.12

Can you update to [0.19.4](https://www.npmjs.com/package/orbit-db) and try again? The latest version should fix this issue (which is indeed from LevelDB as @mmick66 says, due to the differences between node.js level and browser level).

Let us know if you're still experiencing the problem after updating to the latest!

**Pull request merged**
