### PR TITLE
Update peer exchanged

### PR DESCRIPTION
**Pull request by msterle**
Bring https://github.com/orbitdb/orbit-db/pull/606 up to date

### CODE REVIEW

**Comment by msterle** [comment]
Interestingly, these tests pass when running locally, even without the updated `orbit-db-store` package, but fail here on the orbit-db CI. It's possible that this is the sort of timing condition that the `peer.exchanged` test was trying to capture, but I'll have to look into it more - ideally, the tests should pass or fail consistently, independent of environment.

**Comment by aphelionz** [comment]
@msterle Looks like we may have IPFS 0.41 support soon... that could will help.

**Comment by msterle** [comment]
Test fixed by increasing the time between the final `replicate` event received and the test for number of `peer.exchanged` events.

**Comment by aphelionz** [comment]
I'm curious now if the update from #782 will now fix this! Let's see if we can get it into 0.24.0.

**Comment by aphelionz** [comment]
@msterle would you mind rebasing this to the latest master? Super curious to see how the tests do

**Comment by aphelionz** [comment]
@oed I don't think so!

**Comment by oed** [comment]
Updated @aphelionz, looks like tests are failing on master as well.

**Comment by aphelionz** [comment]
@oed @msterle Any chance of getting this rebased one more time now that we have passing tests on master?

**Comment by oed** [comment]
Done @aphelionz

**Pull request merged**
