### PR TITLE
update GUIDE.md according to new constructor of IPFS object

### LINKED ISSUE #846: IPFS is not a constructor
Hi, 
I have been trying to follow the [setup guide](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#setup), 
however, when I run my script with nodejs, I always get the same error:
```
const ipfs = new IPFS(ipfsOptions)
             ^

TypeError: IPFS is not a constructor
    at Object.<anonymous> (/Users/simon/projects/orbitdb/example.js:11:14)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47
```

Here is my code 
``` javascript
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

// Set ipfs options
const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  }
}
// Create IPFS instance
const ipfs = new IPFS(ipfsOptions)

ipfs.on('ready', async () => {
  // Create OrbitDB instance
  const orbitdb = await OrbitDB.createInstance(ipfs)
})
```

And here is how I launch the script from terminal:
``` node example.js```

I have tried to investigate that error, but I am not sure how it relates to the Orbit-DB package.  
Is this a problem with the packaged I installed via npm, or should I add something into my script?

Thanks

### LINKED ISSUE #847: update GUIDE.md, permission denied
Hi, 
I submitted this PR a few days ago https://github.com/orbitdb/orbit-db/issues/846
Since the Doc was outdated, I have updated the GUIDE.md, with my modifications for the examples to work. 
I have no permission to create a branch on the repo for my modifications. Is it possible to get access?
Or should I send my updated GUIDE.md file to someone?

cheers

### PR DESCRIPTION
**Pull request by simonbonnefoy**
I updated the examples in the GUIDE.md.
I modified the constructor of the IPFS object. I checked all the examples, they
seem to be working.
This comes from this issue https://github.com/orbitdb/orbit-db/issues/846, 
where I was told that the documentation needed to be updated. 

I hope it helps

Edit from @aphelionz: fixes #847 and fixes #846

### CODE REVIEW

**Review by aphelionz — APPROVED** [review]
Thanks!

**Comment by aphelionz** [comment]
Re-running CI now

**Comment by simonbonnefoy** [comment]
OK, great thanks!

**Comment by aphelionz** [comment]
The CI fixes aren't related so we can merge. Thanks again!

**Comment by simonbonnefoy** [comment]
OK, great! Thank you

**Pull request merged**
