### PR TITLE
Tyleryasaka peer exchanged

### PR DESCRIPTION
**Pull request by aphelionz**
Creating this PR fo CircleCI tests

### CODE REVIEW

**Comment by oed** [comment]
Any update on this? 🙂

**Comment by oed** [comment]
Ping @aphelionz, is this still something you are going to merge?

**Comment by aphelionz** [comment]
Currently on hold until we can get more input and eyes on the problem being addressed.

**Comment by oed** [comment]
Ok, what do you need? This would be a great feature to have!

**Comment by aphelionz** [comment]
@chmanie - you and I discussed this PR in Berlin. Can refresh my memory and point us all in the right direction to get this feature to where it needs to be to merge?

cc @oed

**Comment by chmanie** [comment]
I think this PR is fine. The one it requires (namely https://github.com/orbitdb/orbit-db-store/pull/38) is not IMHO. The event listeners there need to be cleaned up, otherwise there will be memory leaks.

**Comment by aphelionz** [comment]
I believe this is superceded by #763

**Pull request closed without merging**
