### PR TITLE
Write-permissioned databases

### PR DESCRIPTION
**Pull request by haadcode**
**Work in progress**

- addresses
- write-permissions
- replication
- performance
- use ipfs, no more ipfs-daemon
- async/await
- logging

### CODE REVIEW

**Comment by haadcode** [comment]
Depends on https://github.com/haadcode/ipfs-log/pull/110

**Comment by haadcode** [comment]
Along with the PR, we'll have a brand new Getting Started guide too: https://github.com/orbitdb/orbit-db/blob/feat/write-access/GUIDE.md.

Would love to get comments and feedback on the guide!

**Comment by haadcode** [comment]
Depends on https://github.com/orbitdb/orbit-db-pubsub/pull/3

**Comment by Steake** [comment]
### Super hyped for this to merge to master 🤓

**Comment by haadcode** [comment]
https://github.com/orbitdb/orbit-db-pubsub/pull/3 and https://github.com/orbitdb/ipfs-log/pull/110 were merged yesterday. Moving on to merging and releasing other dependencies today. Getting very close to merging this!

**Comment by haadcode** [comment]
And thank you everyone for the support and love you're sending for this PR! ❤️ 😄

**Comment by haadcode** [comment]
This is now merged! 🎉 🎆 ❤️ 

It has taken a long time to get to this point, but we're finally there. This is the biggest update to OrbitDB since inception bringing in long-requested features and fixes to many of the open issues. I'll make an npm release later today after making sure everything is still working.

Thank you everyone for your help, support and comments throughout the way! ❤️

**Pull request merged**
