### PR TITLE
WIP Adds contract access controller tests

### PR DESCRIPTION
**Pull request by coyotespike**
This PR is WIP. It begins to develop a smart contract access controller.

It also rebases the existing dynamic access branch on master, fixing tests where necessary.

### CODE REVIEW

**Comment by coyotespike** [comment]
The tests pass locally (!), but cannot pass on CircleCI because `npm i` from a specific github branch isn't supported.

**Comment by 509dave16** [comment]
@coyotespike I don't know if I'm in any position to help with this PR. But it looks like the latest circleci tests failed due to the `rest parameter` not being recognized by babel in the test environment. The preset being used should include rest parameters though.

**Comment by coyotespike** [comment]
Thanks @509dave16, I will either remove that parameter or see if babel can include it :+1:

**Comment by coyotespike** [comment]
This PR now adds signing, verification, `getPublicKey`, etc functions to all access controllers, so that they will work with the `acl-refactor` branch on `ipfs-log`.

**Comment by lukas2005** [comment]
Amazing 👍 I hope this gets merged soon because this would really make my work easier :)

**Pull request closed without merging**
